#!/bin/sh
set -eu

# ----------------------------------------------------------------------------------------------------------------------

echo "► Starting Main Entrypoint..."

# --------------------------------------------------------------------------------------------------------------------

# Run Dockerfile's CMD (default: $> php-fpm )
echo "► Starting application with doppler... cmd: ${@}"
if [ -z "${DOPPLER_TOKEN+x}" ]; then
  echo "Doppler token non défini. Commande exécutée sans Doppler."
  exec "$@"
else
  # Pass the command and its arguments to doppler using `--` so they are not treated as a single string
  exec doppler run -- "$@"
fi